<a href="https://colab.research.google.com/github/SilahicAmil/Random-Python-ML-Testing/blob/main/Random_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(1,5):
  print(i)
else:
  print("this is a block statement")

1
2
3
4
this is a block statement


In [ ]:
p,q,r=10,20,30
print(p,q,r)

10 20 30


In [ ]:
x = 36 / 4 * (3 +  2) * 4 + 2
print(x)


182.0


In [ ]:
var = "James" * 2  * 3
print(var)


JamesJamesJamesJamesJamesJames


In [1]:
for x in range(0.5, 5.5, 0.5):
  print(x)

TypeError: ignored

In [ ]:
var1 = 1
var2 = 2
var3 = "3"

print(var + var2 + var3)

TypeError: ignored

In [ ]:
def multiplication_or_sum(num1,num2):
  product= num1*num2
  # check product
  if product < 1000:
    return product
  else:
    return num1 + num2


res = multiplication_or_sum(20,30)
print(f"The result is: {res}")


res = multiplication_or_sum(40,30)
print(f"The result is: {res}")

The result is: 600
The result is: 70


In [ ]:
# x=range(10)
for i in range(10):
  print(x)

range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)


In [ ]:
def sum_num(num):
  prev_num = 0
  for i in range(num):
    sum = prev_num + 1
    print(f"Current Number: 1\n")
    print(f"Previous Number: {prev_num}")
    print(f"Sum: {sum}")
    prev_num = i

res = sum_num(10)
print(res)

Current Number: 1

Previous Number: 0
Sum: 1
Current Number: 1

Previous Number: 0
Sum: 1
Current Number: 1

Previous Number: 1
Sum: 2
Current Number: 1

Previous Number: 2
Sum: 3
Current Number: 1

Previous Number: 3
Sum: 4
Current Number: 1

Previous Number: 4
Sum: 5
Current Number: 1

Previous Number: 5
Sum: 6
Current Number: 1

Previous Number: 6
Sum: 7
Current Number: 1

Previous Number: 7
Sum: 8
Current Number: 1

Previous Number: 8
Sum: 9
None


In [ ]:
for i in range(10):
  print(i + 1)

1
2
3
4
5
6
7
8
9
10


In [ ]:
n=2

for i in range(1,11,1):
  product = n*i
  print(product)

2
4
6
8
10
12
14
16
18
20


In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2])

8


In [8]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [12]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:]) # 3: - Displays the last 4. Backwards index to +1 is added

[4 5 6 7]


In [15]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2]) # :: Makes it so you can print every other.

[1 3 5 7]
