<a href="https://colab.research.google.com/github/SilahicAmil/Random-Python-ML-Testing/blob/main/Random_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(1,5):
  print(i)
else:
  print("this is a block statement")

1
2
3
4
this is a block statement


In [ ]:
p,q,r=10,20,30
print(p,q,r)

10 20 30


In [ ]:
x = 36 / 4 * (3 +  2) * 4 + 2
print(x)


182.0


In [ ]:
var = "James" * 2  * 3
print(var)


JamesJamesJamesJamesJamesJames


In [ ]:
for x in range(0.5, 5.5, 0.5):
  print(x)

TypeError: ignored

In [ ]:
var1 = 1
var2 = 2
var3 = "3"

print(var + var2 + var3)

TypeError: ignored

In [ ]:
def multiplication_or_sum(num1,num2):
  product= num1*num2
  # check product
  if product < 1000:
    return product
  else:
    return num1 + num2


res = multiplication_or_sum(20,30)
print(f"The result is: {res}")


res = multiplication_or_sum(40,30)
print(f"The result is: {res}")

The result is: 600
The result is: 70


In [ ]:
# x=range(10)
for i in range(10):
  print(x)

range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)
range(0, 10)


In [ ]:
def sum_num(num):
  prev_num = 0
  for i in range(num):
    sum = prev_num + 1
    print(f"Current Number: 1\n")
    print(f"Previous Number: {prev_num}")
    print(f"Sum: {sum}")
    prev_num = i

res = sum_num(10)
print(res)

Current Number: 1

Previous Number: 0
Sum: 1
Current Number: 1

Previous Number: 0
Sum: 1
Current Number: 1

Previous Number: 1
Sum: 2
Current Number: 1

Previous Number: 2
Sum: 3
Current Number: 1

Previous Number: 3
Sum: 4
Current Number: 1

Previous Number: 4
Sum: 5
Current Number: 1

Previous Number: 5
Sum: 6
Current Number: 1

Previous Number: 6
Sum: 7
Current Number: 1

Previous Number: 7
Sum: 8
Current Number: 1

Previous Number: 8
Sum: 9
None


In [ ]:
for i in range(10):
  print(i + 1)

1
2
3
4
5
6
7
8
9
10


In [ ]:
n=2

for i in range(1,11,1):
  product = n*i
  print(product)

2
4
6
8
10
12
14
16
18
20


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2])

8


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:]) # 3: - Displays the last 4. Backwards index to +1 is added

[4 5 6 7]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2]) # :: Makes it so you can print every other.

[1 3 5 7]


In [ ]:
import numpy as np

percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype)

float64


In [ ]:
import numpy as np
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print (new_series.ndim)
print (new_series.shape)
print (new_series.dtype)

2
(2, 4)
int64


In [ ]:
x= 30
for i in range (1, x):
  print(i)
else:
  print("console error")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
console error


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
sample_dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])
sample_dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
# For loop iterator
for elem in sample_dataset:
  print(elem.numpy())

1
2
3
4
5
6


In [ ]:
# Reducing dataset
print(sample_dataset.reduce(0, lambda state, value: state + value).numpy()) # Adds all values



21


In [ ]:
# Creating random list of ints
import random

x = [] 


for i in range (0,8):
  y = random.randint(5,40)
  x.append(y)
print(x)

[26, 5, 17, 34, 10, 37, 14, 32]


# Testing out the element_spec for tf.data

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(x)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
# For loop iterator
for elem in dataset:
  print(elem.numpy())

26
5
17
34
10
37
14
32


In [ ]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([2,8]))
dataset1.element_spec

TensorSpec(shape=(8,), dtype=tf.float32, name=None)

In [ ]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-4ea6f717-de98-9b74-4266-dd516265c76b)


# Coding from Python Crash Course 2nd Edition book. Functions and Classes

In [2]:
# Function with arg
def fav_book(book):
  print(f"My Favorite book is: {book.title()} !")
  
fav_book("Deep Learning with Python")

My Favorite book is: Deep Learning With Python !


In [9]:
# Positional args
def desc_animal(animal_type, pet_name):
  """
  Displays animal information
  """

  print(f"\n I have a {animal_type}")
  print(f"My {animal_type}'s name is {pet_name.title()}")

desc_animal("moose", "johnny")
desc_animal("hamster", "mason")




 I have a moose
My moose's name is Johnny

 I have a hamster
My hamster's name is Mason


In [12]:
def get_formatted_name(first_name, last_name):
  """
  Return a full name, neatly formatted
  """

  full_name = f"{first_name} {last_name}"
  return full_name.title()

gamer = get_formatted_name("jacob", "clemenson")
print(gamer)

Jacob Clemenson


In [14]:
# Returning dict and adding age if default changed

def build_person(first_name, last_name, age=None):
  """
  Returns dict of information about person
  """

  person = {"first": first_name,
            "last": last_name,
            }
  if age:
    person["age"] = age
  return person

olympian = build_person("Usain", "Bolt", age=42)
print(olympian)

{'first': 'Usain', 'last': 'Bolt', 'age': 42}
